### ISSUE TITLE
contexts?

### ISSUE THREAD

**Issue by ksonda** [internetofwater/geoconnex.us#89]
Many of the SELFIE contexts in use by SELFIE examples (eg the current waterdata.usgs.gov/monitoring-location pages) don't resolve due to broken links. Should we provide direct hosting/ resolution of contexts, as well as PIDs for context files in case we do have to move them around.\?

**Comment by dblodgett-usgs** [comment]
These should get fixed in SELFIE. Can you point to the ones that are broken?

**Comment by ksonda** [comment]
NVM, its just that the USGS monitoring-location pages reference "https://opengeospatial.github.io/ELFIE/json-ld/elf-index.jsonld", which doesn't resolve but there's new versions at new selfie addresses.
